<?php

namespace Rongu\Sms\Dhiraagu;

enum ResultCode: int {
    case OK = 100;
    case OK_ALT = 0;
    case FAILED_WS = 1;
    case FAILED_WS_INVALID_FIELD = 2;
    case FAILED_WS_MISSING_USERNAME = 3;
    case FAILED_WS_USERNAME_INCLUDES_INVALID_CHARACTERS = 4;
    case FAILED_WS_ILLEGAL_USERNAME_LEN = 5;
    case FAILED_WS_INVALID_EMAIL_ADDRESS = 6;
    case FAILED_WS_USERNAME_NOT_EXISTS = 7;
    case FAILED_WS_INVALID_MOBILE_NUMBER = 15;
    case FAILED_WS_ILLEGAL_ARGUMENTS = 25;
    case FAILED_WS_INVALID_PHONE_NUMBER = 26;
    case FAILED_WS_MISSING_MOBILE = 27;
    case FAILED_WS_MISSING_DEVICES = 28;
    case FAILED_WS_VERIFICATION_FAILED = 32;
    case FAILED_WS_INVALID_ALPHANUMERIC = 35;
    case FAILED_WS_BILLING_FAILED = 36;
    case FAILED_WS_USER_IS_LOCKED = 37;
    case FAILED_WS_INTERNAL_ERROR = 39;
    case FAILED_WS_MISSING_IDENTIFIER = 40;
    case FAILED_WS_USER_NOT_ALLOWED = 41;
    case FAILED_WS_USER_IS_DELETED = 44;
    case FAILED_WS_USER_IS_DISABLED = 45;
    case FAILED_WS_NOT_ENOUGH_CREDIT = 47;
    case FAILED_WS_UNSUPPORTED_MIME_TYPE = 48;
    case FAILED_WS_MAX_FILE_SIZE_VIOLATION = 49;
}