<?php

namespace Rongu\Sms\Vonage;

enum VonageResultCode: int {
    case DELIVERED = 0;
    case UNKNOWN = 1;
    case ABSENT_SUBSCRIBER_TEMPORARY = 2;
    case ABSENT_SUBSCRIBER_PERMANENT = 3;
    case CALL_BARRED_BY_USER = 4;
    case PORTABILITY_ERROR = 5;
    case ANTI_SPAM_REJECTION = 6;
    case HANDSET_BUSY = 7;
    case NETWORK_ERROR = 8;
    case ILLEGAL_NUMBER = 9;
    case ILLEGAL_MESSAGE = 10;
    case UNROUTABLE = 11;
    case DESTINATION_UNREACHABLE = 12;
    case SUBSCRIBER_AGE_RESTRICTION = 13;
    case NUMBER_BLOCKED_BY_CARRIER = 14;
    case PREPAID_INSUFFICIENT_FUNDS = 15;
    case GATEWAY_QUOTA_EXCEEDED = 16;
    case ABNORMAL_SEQUENTIAL_DIALING_DETECTED = 21;
    case ABNORMAL_TRAFFIC_BURST_DETECTED = 22;
    case ILLEGAL_SENDER_ADDRESS_FOR_US_DESTINATION = 39;
    case DAILY_LIMIT_SURPASSED = 41;
    case ENTITY_FILTER = 50;
    case HEADER_FILTER = 51;
    case CONTENT_FILTER = 52;
    case CONSENT_FILTER = 53;
    case REGULATION_ERROR = 54;
    case GENERAL_ERROR = 99;
}